spring:
  datasource:
    url: jdbc:h2:mem:etl;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console
    
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true